services:
  dev-db:
    image: postgres:18
    container_name: voice-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: carodevsql
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ../scripts/sql/users.sql:/docker-entrypoint-initdb.d/01-users.sql:ro
      - ../scripts/sql/refresh-tokens.sql:/docker-entrypoint-initdb.d/02-refresh-tokens.sql:ro
      - ../scripts/sql/profile.sql:/docker-entrypoint-initdb.d/03-profile.sql:ro

volumes:
  db-data: